"""init

Revision ID: c8f54b2d8b6d
Revises: 
Create Date: 2025-11-14 07:36:08.712550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f54b2d8b6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'USER', 'MODERATOR', name='user_role_enum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('nom_projet', sa.String(length=255), nullable=True),
    sa.Column('description_projet', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', name='project_visibility'), server_default='private', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('conversation_title', sa.String(), nullable=False),
    sa.Column('conversation_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['conversation_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('conversation_uuid')
    )
    op.create_index('ix_conversation_project_id', 'conversations', ['conversation_project_id'], unique=False)
    op.create_index('ix_conversation_user_id', 'conversations', ['conversation_user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_project_id', 'chunks', ['chunk_project_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.UUID(), nullable=False),
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('message_sender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['message_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_uuid')
    )
    op.create_index('ix_message_conversation_id', 'messages', ['message_conversation_id'], unique=False)
    op.create_index('ix_message_user_id', 'messages', ['message_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_user_id', table_name='messages')
    op.drop_index('ix_message_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_conversation_user_id', table_name='conversations')
    op.drop_index('ix_conversation_project_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
